import { test } from "node:test";
import assert from "node:assert/strict";
import { access, cp, mkdtemp, readFile, writeFile, rm } from "node:fs/promises";
import path from "node:path";
import os from "node:os";
import { createServer } from "node:http";
import { once } from "node:events";
import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { InMemoryTransport } from "@modelcontextprotocol/sdk/inMemory.js";
import { BrowserAPI } from "../mcp-server/browser-api.js";
import { AgentBrowserAdapter } from "../mcp-server/adapter.js";
import { createMcpServer } from "../mcp-server/mcp.js";
import { launchFirefox } from "./helpers/marionette.js";

const executable = process.env.FIREFOX_PATH || "/opt/zen-browser-bin/zen";
const available = await access(executable).then(() => true, () => false);

test("live Firefox: temporary extension + real MCP core workflow in a disposable profile", { skip: !available && "Set FIREFOX_PATH to test the extension", timeout: 90000 }, async (t) => {
  const temp = await mkdtemp(path.join(os.tmpdir(), "mcp-zen-live-"));
  t.after(() => rm(temp, { recursive: true, force: true }));
  const html = await readFile(new URL("fixtures/page.html", import.meta.url), "utf8");
  const web = createServer((req, res) => {
    res.setHeader("Content-Type", "text/html");
    if (req.url === "/second") res.end("<title>Second</title><h1>Second page</h1>");
    else if (req.url === "/frame") res.end("<title>Pay</title><label>Card number<input id='card'></label><button id='pay'>Pay</button>");
    else res.end(html);
  });
  web.listen(0, "127.0.0.1"); await once(web, "listening");
  t.after(() => { web.closeAllConnections(); web.close(); });
  const url = `http://127.0.0.1:${web.address().port}/`;
  process.env.EXTENSION_PORT = "0";
  process.env.CONTAINERIZED = "1";
  const api = new BrowserAPI(); await api.init(); t.after(() => api.close());
  const extensionDir = path.join(temp, "extension");
  await cp(new URL("../firefox-extension/", import.meta.url), extensionDir, { recursive: true, filter: (source) => !source.includes("node_modules") });
  const background = path.join(extensionDir, "dist/background.js");
  const source = await readFile(background, "utf8");
  assert.ok(source.includes("[8765]"));
  await writeFile(background, source.replace("[8765]", `[${api.wsServer.address().port}]`));
  // Auto-grant optional permissions in this disposable test copy only. Production
  // keeps them optional and requires the user's options-page button clicks.
  const manifestPath = path.join(extensionDir, "manifest.json");
  const manifest = JSON.parse(await readFile(manifestPath, "utf8"));
  manifest.permissions.push(...manifest.optional_permissions);
  manifest.optional_permissions = [];
  await writeFile(manifestPath, JSON.stringify(manifest));
  const firefox = await launchFirefox(executable, { "privacy.userContext.enabled": true });
  t.after(() => firefox.close());
  await firefox.command("Addon:Install", { path: extensionDir, temporary: true });
  for (let i = 0; i < 100 && !api.ws; i++) await new Promise((resolve) => setTimeout(resolve, 50));
  assert.ok(api.ws, "Extension should connect to the isolated test server");
  const adapter = new AgentBrowserAdapter(api, { screenshotDir: temp });
  const server = createMcpServer(adapter);
  const client = new Client({ name: "live-firefox-test", version: "1" });
  const [clientTransport, serverTransport] = InMemoryTransport.createLinkedPair();
  await server.connect(serverTransport); await client.connect(clientTransport);
  t.after(async () => { await client.close(); await server.close(); });
  const call = async (name, args = {}) => {
    const result = await client.callTool({ name: `agent_browser_${name}`, arguments: { ...args, timeoutMs: 10000 } });
    assert.equal(result.isError, false, `${name}: ${result.content[0].text}`);
    return result.structuredContent.response.data;
  };
  const created = await call("tab_new", { url, label: "fixture" });
  assert.equal(created.url, url, "tab_new must await navigation, not report the initial about:blank");
  const snapshot = await call("snapshot");
  const inputRef = Object.entries(snapshot.refs).find(([, ref]) => ref.name === "Full name")[0];
  await call("fill", { selector: `@${inputRef}`, text: "Ada" });
  await call("type", { selector: "#name", text: " Lovelace", delayMs: 1 });
  assert.equal((await call("eval", { script: "document.getElementById('name').value" })).result, "Ada Lovelace");
  await call("check", { selector: "#check" }); await call("uncheck", { selector: "#check" });
  assert.deepEqual((await call("select", { selector: "#select", values: ["red", "Blue"] })).selected, ["red", "blue"]);
  await call("press", { key: "Enter" });
  await call("click", { selector: "#save" });
  await call("wait_for_text", { text: "Saved", waitTimeoutMs: 2000 });
  assert.equal((await call("get_text", { selector: "#status" })).text, "Saved");
  assert.equal((await call("get_title")).title, "Agent compatibility fixture");
  assert.equal((await call("get_url")).url, url);
  await call("scroll", { selector: "#scroller", direction: "right", amount: 50 });
  const image = await call("screenshot", { fullPage: true, annotate: true });
  assert.ok((await readFile(image.path)).length > 100);
  const crop = await call("screenshot", { selector: "#name", format: "jpeg", quality: 70 });
  assert.equal((await readFile(crop.path)).subarray(0, 2).toString("hex"), "ffd8");
  assert.match((await call("read", { outline: true })).content, /Compatibility fixture/);
  await call("find", { locator: "text", value: "Place order", action: "click" });
  assert.equal((await call("get_text", { selector: "#status" })).text, "Ordered");
  assert.equal((await call("is_enabled", { selector: "#disabled" })).enabled, false);
  assert.match((await call("get_attr", { selector: "#link", name: "href" })).value, /\/second/);
  await call("hover", { selector: "#menu-btn" });
  await call("scroll_into_view", { selector: "#place-order" });
  await call("tap", { selector: "#place-order" });
  await call("swipe", { direction: "down", amount: 20 });
  const iframe = await call("frame_switch", { frame: "#pay-frame" });
  assert.ok(Number.isInteger(iframe.frameId) && iframe.frameId !== 0);
  assert.match((await call("get_attr", { selector: "#card", name: "id" })).value || "card", /card/i);
  await call("fill", { selector: "#card", text: "4242" });
  await call("frame_main");
  await call("open", { url: url + "second" });
  assert.match((await call("wait_for_url", { url: "/second", waitTimeoutMs: 5000 })).url, /\/second/);
  await call("eval", { script: "console.log('mcp-zen-console', 1); 'ok'" });
  const logs = await call("console");
  assert.ok((logs.messages || []).some((m) => String(m.text).includes("mcp-zen-console")), JSON.stringify(logs));
  await call("console", { clear: true });
  await call("dialog_status");
  const stale = await client.callTool({ name: "agent_browser_fill", arguments: { selector: `@${inputRef}`, text: "wrong", timeoutMs: 1000 } });
  assert.equal(stale.isError, true);
  await call("back"); await call("forward"); await call("reload");
  await call("wait_for_load", { state: "load" });
  await call("tab_switch", { tab: created.id });
  // Named sessions create real Firefox containers, with separate cookie jars.
  await call("tab_new", { session: "a", url });
  await call("eval", { session: "a", script: "document.cookie = 'isolated=yes'; document.cookie" });
  await call("tab_new", { session: "b", url });
  assert.equal((await call("eval", { session: "b", script: "document.cookie" })).result, "");
  assert.equal((await call("tab_list", { session: "a" })).tabs.length, 1);
  await call("close", { all: true });
});
